### PR TITLE
feat: Light Mode Toggle

### LINKED ISSUE #12: pls make light version
please make white background version these days one can switch between light/dark background.

you should improve your app to do that with bg as well

### PR DESCRIPTION
**Pull request by haaarsh619**
Issue Resolves  #12 

Suggest If We can do anything Differently.

Preview: 

https://github.com/henripar/scrollbar/assets/72140070/21a3b3c7-1691-44dd-85ac-c1aa6e987906

### CODE REVIEW

**Comment by henripar** [comment]
Hi, thanks for the PR!

Few things that could be improved.

Please change the color of these buttons as well. They are now disappearing on light mode. 
Screenshot 2023-09-18 at 19 39 44

Also, please change your linter / formatter settings to use single quotes instead of double quotes to keep it consistent with the codebase. It also makes it easier to view what has been actually changed :)

**Comment by haaarsh619** [comment]
> Hi, thanks for the PR!
> 
> Few things that could be improved.
> 
> Please change the color of these buttons as well. They are now disappearing on light mode. Screenshot 2023-09-18 at 19 39 44
> 
> Also, please change your linter / formatter settings to use single quotes instead of double quotes to keep it consistent with the codebase. It also makes it easier to view what has been actually changed :)

Updated the code.

**Comment by haaarsh619** [comment]
@henripar hello any updates about my PR.

**Review by henripar — APPROVED** [review]

**Comment by henripar** [comment]
Sorry for the delay. Approved and merged. Thanks for the PR :)

**Pull request merged**
